In [17]:
import numpy as np
import cv2
from PIL import Image

In [18]:
from triplerecovery import bits, utils, embed, authenticate, recover

In [19]:
imarr=imarr=np.array(Image.open('art.png').convert('L'))

In [20]:
imarr.shape

(704, 448)

In [21]:
extras = np.array([imarr.shape[0], imarr.shape[1],
                      0], np.uint8)

In [22]:
bti=bits.authentication.make(imarr)

In [23]:
rett=bits.authentication.embed(imarr,bti)

In [24]:
kk=bits.authentication.extract(rett)

In [25]:
kk.shape

(16, 77, 128)

In [26]:
kk[0][0]

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

In [27]:
bti[0][0]

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=object)

In [28]:
np.packbits(kk[0][15].astype(bool))

array([102, 248,  49,  80,  31, 214, 141, 109,  83, 254, 211,  68,  11,
         7,   0,  15], dtype=uint8)

In [29]:
np.packbits(bti[0][15].astype(bool))

array([102, 248,  49,  80,  31, 214, 141, 109,  83, 254, 211,  68,  11,
         7,   0,  15], dtype=uint8)

In [30]:
extras=kk[:,:,-4*8:]
extras

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 1],
        [0, 0, 0, ..., 1, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 1],
        [0, 0, 0, ..., 1, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 1],
        [0, 0, 0, ..., 1, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 1],
        [0, 0, 0, ..., 1, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 

In [34]:
extras.shape

(16, 77, 32)

In [36]:
ret=np.packbits(extras.astype(bool),axis=2)

In [71]:
(_, idx, counts) = np.unique(ret[:,:,3], return_index=True, return_counts=True)
index = idx[np.argmax(counts)]
mode = ret[0,0,3]

In [72]:
idx, counts

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76, 321,
        322, 323, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
        152, 153, 337, 338, 339, 218, 219, 220, 221, 222, 223, 224, 225,
        226, 227, 228, 229, 230, 353, 354, 355, 295, 296, 297, 298, 299,
        300, 301, 302, 303, 304, 305, 306, 307, 369, 370, 371, 616, 617,
        618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630,
        631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643,
        644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656,
        657, 658, 659, 660, 661, 662, 663, 664, 665

In [73]:
index

295

In [80]:
ret[:,:,3].reshape(-1)

array([  0,   1,   2, ..., 250, 251, 252], dtype=uint8)

In [74]:
ret.shape

(16, 77, 4)

In [75]:
mode

0